# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ buildGoPackage, fetchgit,
  procps, iproute, which, findutils
}:

buildGoPackage rec {
  name = "batexpe-${version}";
  version = "1.0.0";
  rev = "3e80900c7b4fca8211e059df0fc548d9b32e3477";

  goPackagePath = "gitlab.inria.fr/batsim/batexpe";

  src = fetchgit {
    inherit rev;
    url = "https://gitlab.inria.fr/batsim/batexpe.git";
    sha256 = "1h3b6j423bcfp3wi1wkjxcd467m61s9hry87ghaf8ayf288py0xh";
  };

  runtimeDependencies = [procps iproute];
  buildInputs = runtimeDependencies ++ [which findutils];

  patchPhase = ''
    # Batexpe binaries have runtime dependencies to multiple programs.
    # This patch changes the code so it calls the realpath of the needed
    # program, so that nix can determine this is a runtime dependency.
    # For example, batexpe will run "/nix/store/.../bin/ss" instead of "ss".

    ########
    # bash #
    ########
    find . -type f -maxdepth 1 -name '*.go' \
      -exec sed -i -e "sW\"bash\"W\"$(which bash)\"Wg" {} \;

    #######################
    # "Real" dependencies #
    #######################
    # ps
    find . -type f -maxdepth 1 -name '*.go' \
      -exec sed -i -e "sW\"ps\"W\"$(which ps)\"Wg" {} \;

    # ss
    find . -type f -maxdepth 1 -name '*.go' \
      -exec sed -i -e "sW\"ss\"W\"$(which ss)\"Wg" {} \;

    ####################################
    # File preview and partial reading #
    ####################################
    # wc
    find . -type f -maxdepth 1 -name '*.go' \
      -exec sed -i -e "sW\"wc\"W\"$(which wc)\"Wg" {} \;

    # head
    find . -type f -maxdepth 1 -name '*.go' \
      -exec sed -i -e "sW\"head\"W\"$(which head)\"Wg" {} \;

    # tail
    find . -type f -maxdepth 1 -name '*.go' \
      -exec sed -i -e "sW\"tail\"W\"$(which tail)\"Wg" {} \;
  '';

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
