# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "batexpe-unstable-${version}";
  version = "2018-01-26";
  rev = "7d9a5f276caa14465a04fa6f4e023f4733e64c30";

  goPackagePath = "gitlab.inria.fr/batsim/batexpe";

  src = fetchgit {
    inherit rev;
    url = "https://gitlab.inria.fr/batsim/batexpe.git";
    sha256 = "15zfpqhvvhph32k94zpdrvz5ms35039293kh77si15dnf3jqaarc";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
