# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/anmitsu/go-shlex";
    fetch = {
      type = "git";
      url = "https://github.com/anmitsu/go-shlex";
      rev = "648efa622239a2f6ff949fed78ee37b48d499ba4";
      sha256 = "10rgdp5d106iisgz25ic8k6f44s9adh4sjh6fyxq9ccm21gw49b7";
    };
  }
  {
    goPackagePath = "github.com/docopt/docopt-go";
    fetch = {
      type = "git";
      url = "https://github.com/docopt/docopt-go";
      rev = "ee0de3bc6815ee19d4a46c7eb90f829db0e014b1";
      sha256 = "0hlra7rmi5pmd7d93rv56ahiy4qkgmq8a6mz0jpadvbi5qh8lq6j";
    };
  }
  {
    goPackagePath = "github.com/ghodss/yaml";
    fetch = {
      type = "git";
      url = "https://github.com/ghodss/yaml";
      rev = "0ca9ea5df5451ffdf184b4428c902747c2c11cd7";
      sha256 = "0skwmimpy7hlh7pva2slpcplnm912rp3igs98xnqmn859kwa5v8g";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "768a92a02685ee7535069fc1581341b41bab9b72";
      sha256 = "1m67cxb6p0zgq0xba63qb4vvy6z5d78alya0vnx5djfixygiij53";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "1875d0a70c90e57f11972aefd42276df65e895b9";
      sha256 = "1kprrdzr4i4biqn7r9gfxzsmijya06i9838skprvincdb1pm0q2q";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "37707fdb30a5b38865cfb95e5aab41707daec7fd";
      sha256 = "1abrr2507a737hdqv4q7pw7hv6ls9pdiq9crhdi52r3gcz6hvizg";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "d670f9405373e636a5a2765eea47fac0c9bc91a4";
      sha256 = "1w1xid51n8v1mydn2m3vgggw8qgpd5a5sr62snsc77d99fpjsrs0";
    };
  }
]
