# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "b3c9a1d25cfbbbab0ff4780b71c4f54e6e92a0de";
      sha256 = "0p823zh1fx3xf8fr3i2xfzrssvg3f45agd7hnr4mqvwsxjgmysyb";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "810d7000345868fc619eb81f46307107118f4ae1";
      sha256 = "07lm9h86l29dd45ca3vjsi06xpwg36899hf1ns7qwabflzgm0nxy";
    };
  }
]
