# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gocov-xml-unstable-${version}";
  version = "2018-04-29";
  rev = "dee33fe4b4adad5fdcad993f498fb4450d5be0a1";

  goPackagePath = "github.com/AlekSi/gocov-xml";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/AlekSi/gocov-xml";
    sha256 = "1gxqwazkq6q5ybfr0nl94lwr55670mrk2503n65059li5hcixazx";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
