# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/axw/gocov";
    fetch = {
      type = "git";
      url = "https://github.com/axw/gocov";
      rev = "3a69a0d2a4ef1f263e2d92b041a69593d6964fe8";
      sha256 = "0djav544wxwi8s2ziqn6ph1v31157k9r9iziqas362smh4fx77hm";
    };
  }
]
