# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gocov-unstable-${version}";
  version = "2017-03-22";
  rev = "3a69a0d2a4ef1f263e2d92b041a69593d6964fe8";

  goPackagePath = "github.com/axw/gocov";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/axw/gocov";
    sha256 = "0djav544wxwi8s2ziqn6ph1v31157k9r9iziqas362smh4fx77hm";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
