# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gocovmerge-unstable-${version}";
  version = "2016-03-31";
  rev = "b5bfa59ec0adc420475f97f89b58045c721d761c";

  goPackagePath = "github.com/wadey/gocovmerge";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/wadey/gocovmerge";
    sha256 = "00m7kxcmmw0l9z0m7z6ii06n5j4bcrxqjbhxjbfzmsdgdsvkic31";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
